# Generated by Django 5.0.2 on 2024-02-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('postal_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CLUB_ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('code_qpv', models.CharField(max_length=100)),
                ('nom_qpv', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('statut_geo', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('federation', models.CharField(max_length=100)),
                ('clubs', models.CharField(max_length=100)),
                ('epa', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DGeographie',
            fields=[
                ('code_commune_geo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('code_qpv_geo', models.CharField(max_length=255)),
                ('commune_geo', models.CharField(max_length=255)),
                ('departement_geo', models.CharField(max_length=255)),
                ('region_geo', models.CharField(max_length=255)),
                ('statut_geo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('code_federation', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nom_federation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ODS_lic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commune', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('code_qpv', models.CharField(max_length=255)),
                ('nom_qpv', models.CharField(max_length=255)),
                ('departement', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('statut_geo', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('federation', models.CharField(max_length=255)),
                ('f_1_4_ans', models.CharField(default='0', max_length=255)),
                ('f_5_9_ans', models.CharField(default='0', max_length=255)),
                ('f_10_14_ans', models.CharField(default='0', max_length=255)),
                ('f_15_19_ans', models.CharField(default='0', max_length=255)),
                ('f_20_24_ans', models.CharField(default='0', max_length=255)),
                ('f_25_29_ans', models.CharField(default='0', max_length=255)),
                ('f_30_34_ans', models.CharField(default='0', max_length=255)),
                ('f_35_39_ans', models.CharField(default='0', max_length=255)),
                ('f_40_44_ans', models.CharField(default='0', max_length=255)),
                ('f_45_49_ans', models.CharField(default='0', max_length=255)),
                ('f_50_54_ans', models.CharField(default='0', max_length=255)),
                ('f_55_59_ans', models.CharField(default='0', max_length=255)),
                ('f_60_64_ans', models.CharField(default='0', max_length=255)),
                ('f_65_69_ans', models.CharField(default='0', max_length=255)),
                ('f_70_74_ans', models.CharField(default='0', max_length=255)),
                ('f_75_79_ans', models.CharField(default='0', max_length=255)),
                ('f_80_99_ans', models.CharField(default='0', max_length=255)),
                ('f_nr', models.CharField(default='0', max_length=255)),
                ('h_1_4_ans', models.CharField(default='0', max_length=255)),
                ('h_5_9_ans', models.CharField(default='0', max_length=255)),
                ('h_10_14_ans', models.CharField(default='0', max_length=255)),
                ('h_15_19_ans', models.CharField(default='0', max_length=255)),
                ('h_20_24_ans', models.CharField(default='0', max_length=255)),
                ('h_25_29_ans', models.CharField(default='0', max_length=255)),
                ('h_30_34_ans', models.CharField(default='0', max_length=255)),
                ('h_35_39_ans', models.CharField(default='0', max_length=255)),
                ('h_40_44_ans', models.CharField(default='0', max_length=255)),
                ('h_45_49_ans', models.CharField(default='0', max_length=255)),
                ('h_50_54_ans', models.CharField(default='0', max_length=255)),
                ('h_55_59_ans', models.CharField(default='0', max_length=255)),
                ('h_60_64_ans', models.CharField(default='0', max_length=255)),
                ('h_65_69_ans', models.CharField(default='0', max_length=255)),
                ('h_70_74_ans', models.CharField(default='0', max_length=255)),
                ('h_75_79_ans', models.CharField(default='0', max_length=255)),
                ('h_80_99_ans', models.CharField(default='0', max_length=255)),
                ('h_nr', models.CharField(default='0', max_length=255)),
                ('nr_nr', models.CharField(default='0', max_length=255)),
                ('total', models.CharField(default='0', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrancheAge',
            fields=[
                ('code_age', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('label_age', models.CharField(default='0', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('code_club', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_club', models.IntegerField()),
                ('nombre_epa', models.IntegerField()),
                ('code_commune_geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dgeographie')),
                ('code_federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.federation')),
            ],
        ),
        migrations.CreateModel(
            name='FLicence',
            fields=[
                ('Nombre_licence', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('code_commune_geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dgeographie')),
                ('code_federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.federation')),
                ('tranche_age_licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trancheage')),
            ],
        ),
    ]
